name: Build InvictusSync

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Instalar RyzenStaff como dependencia local
        run: mvn install:install-file -Dfile=libs/RyzenStaff.jar -DgroupId=dev.imshadow -DartifactId=RyzenStaff -Dversion=2.0.8 -Dpackaging=jar

      - name: Compilar con Maven
        run: mvn package -DskipTests

      - name: Subir JAR compilado
        uses: actions/upload-artifact@v4
        with:
          name: InvictusSync
          path: target/InvictusSync-1.0.0.jar
