name: Build InvictusSync

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install RyzenStaff dependency
        run: |
          mvn install:install-file \
          -Dfile=libs/RyzenStaff.jar \
          -DgroupId=dev.imshadow \
          -DartifactId=RyzenStaff \
          -Dversion=2.0.8 \
          -Dpackaging=jar

      - name: Build plugin
        run: mvn clean package -DskipTests

      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: InvictusSync
          path: target/*.jar
